foreground #e0e2ea
background #14161b

selection_foreground #e0e2ea
selection_background #4f5258

cursor #e0e2ea
cursor_text_color #14161b

active_tab_foreground #e0e2ea
active_tab_background #2c2e33
inactive_tab_foreground #9b9ea4
inactive_tab_background #07080d
tab_bar_background #07080d

color0 #14161b
color1 #ffc0b9
color2 #b3f6c0
color3 #fce094
color4 #a6dbff
color5 #ffcaff
color6 #8cf8f7
color7 #e0e2ea
color8 #4f5258
color9 #ffc0b9
color10 #b3f6c0
color11 #fce094
color12 #a6dbff
color13 #ffcaff
color14 #8cf8f7
color15 #07080d
